### ISSUE TITLE
RFC: Remove `NO_CONFLICT` fallbacks

### ISSUE THREAD

**Issue by mihaibivol** [inspirehep/json-merger#19]
No conflict fallbacks for `default_dict_merger_op` are misleading since adding this operation to the merger does not filter all conflicts and only those that do not appear in list fields.

Most probably in every use-case of the merger the `merger.merge()` call will be surrounded by a `try: except` block. Rather than adding both conflict filtering configuration options and also other custom logic in the `try: except` block (since we can't add every conflict resolution as an operation) we could allow the user to filter out conflicts on each class use.

**Comment by mihaibivol** [comment]
@kaplun WDYT?

**Comment by kaplun** [comment]
@mihaibivol coming back to this one, is it still relevant? Can you make an example to clarify what you meant?

**Comment by mihaibivol** [comment]
The config options for merging `head` with `update` on top of a `root` record are:

For object, string, number fields e g. head: `{'foo': 'bar'}`, update: `{'foo': 'baz'}`
- Fallback Keep Head Conflict - result is `{'foo': ' bar'}` and a conflict is raised to say don't you want to set `'foo'` to `'baz'` instead.
- Fallback Keep Head No Conflict -  result is `{'foo': ' bar'}` and no conflict is raised
- Fallback Keep Update No Conflict -  result is `{'foo': ' baz'}` and a conflict is raised to say don't you want to set `'foo'` to `'bar'` instead.
- Fallback Keep Update Conflict - result is `{'foo': ' baz'}` and no conflict is raised

For List fields
Keep Update And Head Entities Update First - Try to keep the order of entities with proiority to update entities. Raise Conflict if we can't
Keep Update And Head Entities Head First - Try to keep the order of entities with prority tp head entities. Raise Conflict if we can't
Keep Update Entities Conflict On Head Delete - Raise a conflict if we remove something from HEAD
Keep Only Head Entities - No conflict
Keep Only Update Entities - No conflict

It's really weird that we have NO_CONFLICT setting only for regular fields (non list ones) so I'd rather remove this config option alltogether and just let the caller silence the exceptions and store only the ones that are relevant for the merging scenario.

It's weird to add a NO_CONFLICT setting and then have your code raising exceptions

**Comment by mihaibivol** [comment]
Sliently pushed to master
