### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kaplun** [inspirehep/json-merger#20]
Documentation is needed in order to describe json-merger usage. In particular:
- What are the concepts behind to be aware of
- How can one write configuration
- What building blocks already exist out of the box and how can one add more.

**Comment by mihaibivol** [comment]
@jacquerie I'll start this list in which I put the pieces that need both documentation and a quick review so we can split it into multiple steps:
- Main Merger:
  - [ ] review
  - [ ] document
- Object Merger:
  - [ ] review
  - [ ] document
- List Aligner: 
  - [ ] review
  - [ ] document
- Matcher and Order Preservation:
  - [ ] review
  - [ ] document
- Utils:
  - [ ] review
  - [ ] document
- Contrib:
  - [ ] review
  - [ ] document

**Comment by kaplun** [comment]
Closed in 8499954b3826ecd4ebdb353eb528c46d98cf53af
