### ISSUE TITLE
Make Matches Transitive

### ISSUE THREAD

**Issue by mihaibivol** [inspirehep/json-merger#22]
For merging and matching list elements the following thing is not transitive and produces weird behavior:

```
H = [.., x, ... ]
R = [.., y, ... ]
U = [.., z, ...]
```

In `KEEP_HEAD` mode for example:

if `x == z` and `z == y`, but `x != z`, `y` won't be taken as a common base since the relation `z == y` won't be taken into account

**Comment by kaplun** [comment]
closed in dbc1d7d2853bcd35c20bd1cedb45c94b379d587c
