### ISSUE TITLE
JSON merger

### ISSUE THREAD

**Issue by jalavik** [inspirehep/json-merger#5]
See below comment from @mihaibivol for use cases.

**Comment by mihaibivol** [comment]
I'll give a bit more context here:

Assuming that for every record we have a `latest_arxiv` and `latest_published` metadata dictionaries the merger will work in the following way given the current state of the record (named `head`):
- [x] arXiv update comes (`update`) and no `latest_published` record is present:
  - merge `new_arxiv` with `head` on top of  `latest_arxiv`
  - for every conflict keep `head` as a fallback and raise a conflict with what `new_arxiv` contained for that field. The conflict can be either `REMOVE key1.key2.key3.key3 None` or `SET_FIELD key1.key2.key3 update_val` 
  - for every list we can configure to:
    - **merge all elements from both lists** and if the elements represent the same entity (e.g. `authors.affiliations`)  merge their records. We can order them on different heuristics. See `tests/test_list_align.py` for that.
    - **keep only the elements in the update** and merge matching entities as above (same conflict rules).
    - **keep only the elements in head** and merge the matching entities as above
    - **keep only the elements in the update** and raise an error if something added in `head` was deleted. The error tells you which elements to put back.
- [x] publisher update comes - same treatment as for arXiv without any published version.
- [ ] arXiv update comes (`update`); we have a `latest_published` (we'll call it `sot` - short for source of truth) and we have a `latest_arxiv` or an empty object (we'll call it `root`). The merge technique will be done in two steps:
  - merge `update` and `sot` on top of `{}`, using the same heuristics in the "arXiv update" section, but on any conflict resolve to `sot` without raising any error. This way we merge out any metadata change that is   owned by the **source of truth record**. We call the merged record `R1`
  - merge `R1` and `head` on top of `root` and keep the same logic as in `arXiv update` or choose to silence some conflicts that are given by manual changes in `head`

**Comment by mihaibivol** [comment]
cc @kaplun, @jalavik, @jmartinm + add any other interested in this. I added the base use cases and ticked what is already implemented.

**Comment by kaplun** [comment]
CC: @annetteholtkamp, @tsgit

**Comment by mihaibivol** [comment]
For everyone CCd. I merged into master the first working version of a merger.

To check the API usage the best place to start is [this](https://github.com/inspirehep/json-merger/blob/master/tests/acceptance/test_merger_update.py)

To check update scenarios and foolproof them to the test [fixtures](https://github.com/inspirehep/json-merger/blob/master/tests/fixtures/update_scenarios)

The semantics of the fixtures are:
- `root.json` latest harvested paper from `SOURCE`
- `head.json` curator enriched record (The one that we would store in the db and display it)
- `update.json` new harvest from `SOURCE`
- `expected.json` Expected fallback values and if conflicts exist, expected conflict body.
  - The conflict body contains (`ACTION`, `FIELD`, `ACTION_VALUE`) and it's an alternative to the current fallback.
- `description.txt` Short human readable description of what we are testing.

**Comment by mihaibivol** [comment]
@jalavik This issue is pretty generic and the use-cases diverged a bit since last update.
